# Generated by Django 4.2.6 on 2023-11-11 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('dl_dst', 'Dl Dst'), ('dl_src', 'Dl Src'), ('in_port', 'In Port'), ('ip_proto', 'Ip Proto'), ('tcp_dst', 'Tcp Dst')], max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('redirect', 'Redirect')], max_length=50)),
                ('conditions', models.ManyToManyField(to='policy_resolver.conditionrule')),
            ],
            options={
                'verbose_name': 'PolicyRule',
                'verbose_name_plural': 'PolicyRules',
            },
        ),
        migrations.CreateModel(
            name='PolicyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_id', models.CharField(max_length=50, unique=True)),
                ('target', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('rules', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policyrecord', to='policy_resolver.policyrule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
