# Generated by Django 4.2.6 on 2023-10-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("port", models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dl_dst", models.CharField(blank=True, max_length=17, null=True)),
                ("dl_src", models.CharField(blank=True, max_length=17, null=True)),
                ("in_port", models.IntegerField(blank=True, null=True)),
                ("ip_proto", models.IntegerField(blank=True, null=True)),
                ("tcp_dst", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Switch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("manufacturer", models.CharField(max_length=50)),
                ("hardware", models.CharField(max_length=50)),
                ("serial_number", models.CharField(max_length=50)),
                ("connected", models.BooleanField(default=False)),
                ("dpid", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Switch",
                "verbose_name_plural": "Switches",
            },
        ),
        migrations.CreateModel(
            name="FlowEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idle_timeout", models.IntegerField(blank=True, null=True)),
                ("cookie", models.IntegerField(blank=True, null=True)),
                ("packet_count", models.IntegerField(blank=True, null=True)),
                ("hard_timeout", models.IntegerField(blank=True, null=True)),
                ("byte_count", models.IntegerField(blank=True, null=True)),
                ("duration_sec", models.IntegerField(blank=True, null=True)),
                ("duration_nsec", models.IntegerField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("flags", models.IntegerField(blank=True, null=True)),
                ("table_id", models.IntegerField(blank=True, null=True)),
                (
                    "actions",
                    models.ManyToManyField(
                        blank=True, null=True, to="command_pusher.action"
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flowentry",
                        to="command_pusher.match",
                    ),
                ),
                (
                    "switch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="command_pusher.switch",
                    ),
                ),
            ],
        ),
    ]
