# Generated by Django 4.2.6 on 2023-11-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='device_id',
            new_name='device_ip',
        ),
    ]
